image: docker:stable

services:
  - postgres:latest
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  POSTGRES_DB: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pg@123
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - build
  - test

maven-build:
  image: maven:3-jdk-11
  image: mdillon/postgis:latest
  stage: build
  script: "mvn -f nemo/pom.xml compile"

maven-test:
  image: maven:3-jdk-11
  image: mdillon/postgis:latest
  stage: test
  script: "mvn -f nemo/pom.xml clean install"

