image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  REPOSITORY: pi-1sem-2021
  NAME_PROJECT: nemo
  REGISTRY: registry.gitlab.com/pi-1sem-2021
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end"
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=.m2/pi-1sem-2021"
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - test
  - package
  - deploy 

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn -f nemo/pom.xml compile"

maven-test:
  image: maven:3-jdk-11
  stage: test
  script: "mvn -f nemo/pom.xml clean install"
