--- 
maven-build: 
  image: maven:3-jdk-11
  script: mvn -f nemo/pom.xml compile
  services: 
    - postgres:latest
  stage: build
maven-test: 
  image: maven:3-jdk-11
  before_script: 
    - adduser postgres
    - ""
    - apt-get update
    - apt-get -y install postgresql
    - apt-get -y install postgresql-client
    - apt-get -y install postgis
  script:
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql --username $POSTGRES_USER --host postgres -d $POSTGRES_DB -c "CREATE EXTENSION IF NOT EXISTS postgis;"
    - mvn -f nemo/pom.xml test
  services: 
    - postgres:latest
    - liquibase/liquibase
    - postgis/postgis:latest
  stage: test
  variables:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: admin
    POSTGRES_HOST_AUTH_METHOD: trust
stages: 
  - build
  - test
