--- 
maven-build: 
  image: "maven:3-jdk-11"
  script: "mvn -f nemo/pom.xml compile"
  services: 
    - "postgres:latest"
  stage: build
maven-test: 
  image: "maven:3-jdk-11"
  script: 
    - docker-compose up -d
    - "mvn -f nemo/pom.xml install"
  services: 
    - "postgres:latest"
    - liquibase/liquibase
    - "mdillon/postgis:latest"
  stage: test
stages: 
  - build
  - test
