image: maven:3-jdk-11

stages:
  - build
  - test
  - package
  - deploy 

maven-build:
  stage: build
  script: "mvn -f nemo/pom.xml compile"

maven-build:
  stage: test
  script: "mvn -f nemo/pom.xml clean install"
