image: docker:latest
services:
  - docker:dind

maven-build: 
  image: "maven:3-jdk-11"
  script: "mvn -f nemo/pom.xml compile"
  services: 
    - "postgres:latest"
  stage: build
maven-test: 
  image: "maven:3-jdk-11"
  script: 
    - "adduser postgres"
    - ""
    - "apt-get update"
    - "apt-get -y install postgresql"
    - "apt-get -y install postgis"
    - su postgres
    - "psql -h \"postgres\" -U postgres -c \"ALTER USER postgres WITH PASSWORD 'admin'\" -d template1"
    - export PGPASSWORD='admin'
    - psql -version
    - "psql -h \"postgres\" -U postgres -c \"create extension postgis;\""
    - "mvn -f nemo/pom.xml test"
  services: 
    - "postgres:latest"
    - liquibase/liquibase
    - mdillon/postgis:latest
  stage: test
  variables: 
    EXTDIR: /usr/share/postgresql/13/extension/
    PGDATA: /var/lib/postgresql/data
    POSTGRES_DB: postgres
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_PASSWORD: admin
    POSTGRES_USER: postgres
    PSQL: "psql -v ON_ERROR_STOP=1"
stages: 
  - build
  - test

