
stages: 
  - build
  - test

maven-build: 
  image: "maven:3-jdk-11"
  script: "mvn -f nemo/pom.xml compile"
  services: 
    - "postgres:latest"
  stage: build

maven-test: 
  image: "maven:3-jdk-11"
  script:
    - "adduser postgres"
    - ""
    - "apt-get update"
    - apt-get install postgresql
    - apt-get install postgis
    - psql -h "postgis" -U postgres -d postgres -c "create extension postgis"
    - "mvn -f nemo/pom.xml test"
  services: 
    - "postgres:latest"
    - liquibase/liquibase
    - mdillon/postgis:latest
  variables: 
    POSTGRES_DB: postgres
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_PASSWORD: admin
    POSTGRES_USER: postgres
    PGDATA: /var/lib/postgresql/data
    EXTDIR: /usr/share/postgresql/13/extension/
    PSQL: psql -v ON_ERROR_STOP=1
  stage: test

