image: docker:latest
services:
  - docker:dind

maven-build: 
  image: "maven:3-jdk-11"
  script: "mvn -f nemo/pom.xml compile"
  services: 
    - "postgres:latest"
  stage: build
  
maven-test: 
  image: "ubuntu:18.04"
  script:
    - apt-get update
    - apt-get -y install postgresql-10
    - apt-get -y install postgresql-10-postgis-2.4
    - apt-get -y install postgresql-10-postgis-scripts
    - apt-get -y install postgis
    - apt-get -y install default-jdk
    - apt-get -y install maven
    - passwd postgres
    - admin
    - admin
    - su postgres
    - "psql -h localhost -U postgres -W admin -c \"ALTER USER postgres WITH PASSWORD 'admin'\" -d template1"
    - "psql -h localhost -U postgres -c \"create extension postgis;\""
    - "mvn -f nemo/pom.xml test"
  services: 
    - "postgres:latest"
    - liquibase/liquibase
    - mdillon/postgis:latest
  stage: test
stages: 
  - build
  - test
