--- 
maven-build: 
  image: "maven:3-jdk-11"
  script: "mvn -f nemo/pom.xml compile"
  services: 
    - "postgres:latest"
  stage: build
maven-test: 
  image: "maven:3-jdk-11"
  liquibase: 
    image: anardy/liquibase
    stage: liquibase
  postgis: 
    image: "postgis:latest"
    stage: postgis
  script: "mvn -f nemo/pom.xml clean install"
  services: 
    - "postgres:latest"
  stage: test
stages: 
  - build
  - test
variables: 
  DOCKER_DRIVER: overlay2
  POSTGRES_DB: postgres
  POSTGRES_HOST: docker
  POSTGRES_HOST_AUTH_METHOD: trust
  POSTGRES_PASSWORD: pg@123
  POSTGRES_USER: postgres

