--- 
maven-build: 
  image: "maven:3-jdk-11"
  script: "mvn -f nemo/pom.xml compile"
  services: 
    - "postgres:latest"
  stage: build
maven-test: 
  before_script: 
    - "adduser postgres"
    - ""
    - "apt-get update"
    - apt -y install postgresql-12 postgresql-client-12
    - apt install postgis postgresql-12-postgis-3
    - apt-get install postgresql-12-postgis-3-scripts
  image: "maven:3-jdk-11"
  script: 
    - "mvn -f nemo/pom.xml test"
  services: 
    - "postgres:latest"
    - liquibase/liquibase
    - "postgis/postgis:latest"
  stage: test
  variables: 
    POSTGRES_DB: postgres
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_PASSWORD: admin
    POSTGRES_USER: postgres
stages: 
  - build
  - test
