--- 
maven-build: 
  image: "maven:3-jdk-11"
  script: "mvn -f nemo/pom.xml compile"
  services: 
    - "postgres:latest"
  stage: build
maven-test: 
  before_script: 
    - "adduser postgres"
    - ""
    - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    - apt-get update
    - apt-get -y install postgresql
    - su postgres
    - psql -c "ALTER USER POSTGRES WITH PASSWORD 'admin'" -d template1
    - psql -c "create database postgres"
    - CREATE EXTENSION postgis;
  image: "maven:3-jdk-11"
  script: "mvn -f nemo/pom.xml test"
  services: 
    - "postgres:latest"
    - liquibase/liquibase
    - postgis/postgis
  stage: test
stages: 
  - build
  - test

