--- 
maven-build: 
  image: "maven:3-jdk-11"
  script: "mvn -f nemo/pom.xml compile"
  services: 
    - "postgres:latest"
  stage: build
maven-test: 
  before_script: 
    - "adduser postgres"
    - ""
    - su postgres
    - psql -c "ALTER USER POSTGRES WITH PASSWORD 'admin'" -d template1
    - psql 
    - create database postgres;
    - CREATE EXTENSION postgis;
  image: "maven:3-jdk-11"
  script: "mvn -f nemo/pom.xml test"
  services: 
    - "postgres:latest"
    - liquibase/liquibase
    - postgis/postgis
  stage: test
stages: 
  - build
  - test

