image: maven:3-jdk-11

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pg@123
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - build
  - test
  - package
  - deploy 

maven-build:
  stage: build
  script: "mvn -f nemo/pom.xml compile"

maven-test:
  stage: test
  script: "mvn -f nemo/pom.xml clean install"
