image: docker:latest
services:
  - docker:dind

maven-build: 
  image: "maven:3-jdk-11"
  script: "mvn -f nemo/pom.xml compile"
  services: 
    - "postgres:latest"
  stage: build
  
maven-test: 
  image: "ubuntu:18.04"
  script:
    - "adduser postgres"
    - ""
    - apt-get update
    - apt-get -y install postgresql-10
    - apt-get -y install postgresql-10-postgis-2.4
    - apt-get -y install postgresql-10-postgis-scripts
    - apt-get -y install postgis-2.4
    - apt-get -y install default-jdk
    - apt-get -y install maven
    - su postgres
    - "psql -c \"ALTER USER postgres WITH PASSWORD 'admin'\" -d template1"
    - export PGPASSWORD='admin'
    - "psql -U postgres -d postgres -c \"create extension postgis;\""
    - "mvn -f nemo/pom.xml test"
  variables: 
    EXTDIR: /usr/share/postgresql/13/extension/
    PGDATA: /var/lib/postgresql/data
    POSTGRES_DB: postgres
    POSTGRES_HOST_AUTH_METHOD: trust
    POSTGRES_PASSWORD: admin
    POSTGRES_USER: postgres
    PSQL: "psql -v ON_ERROR_STOP=1"
  stage: test
stages: 
  - build
  - test
