INSERT INTO course VALUES
('Implementação'),
('Táticas'),
('Táticas'),
('Fatores'),
('Otimização'),
('Prestação de contas'),
('Diretivas'),
('Fatores'),
('Soluções'),
('Marca'),
('Programa'),
('Soluções'),
('Comunicações'),
('Identidade'),
('Programa'),
('Funcionalidade'),
('Mobilidade'),
('Programa'),
('Qualidade'),
('Otimização'),
('Mobilidade'),
('Rede'),
('Prestação de contas'),
('Prestação de contas'),
('Rede'),
('Operações'),
('Rede'),
('Funcionalidade'),
('Programa'),
('Operações'),
('Configuração'),
('Soluções'),
('Mobilidade'),
('Contas'),
('Integração'),
('Divisão'),
('Branding'),
('Criativo'),
('Funcionalidade'),
('Grupo'),
('Grupo'),
('Programa'),
('Mobilidade'),
('Mercados'),
('Soluções'),
('Implementação'),
('Resposta'),
('Rede'),
('A infraestrutura'),
('Usabilidade'),
('Contas'),
('Funcionalidade'),
('Aplicações'),
('Rede'),
('Operações'),
('Rede'),
('Implementação'),
('A infraestrutura'),
('Branding'),
('A infraestrutura'),
('A infraestrutura'),
('Métricas'),
('Operações'),
('Garantia'),
('Contas'),
('Integração'),
('Divisão'),
('Mobilidade'),
('Branding'),
('Funcionalidade'),
('Mobilidade'),
('Dados'),
('Interações'),
('Mobilidade'),
('Programa'),
('Métricas'),
('Fatores'),
('Comunicações'),
('Funcionalidade'),
('Programa'),
('Marketing'),
('Garantia'),
('A infraestrutura'),
('Implementação'),
('A infraestrutura'),
('Configuração'),
('Paradigma'),
('A infraestrutura'),
('Fatores'),
('Táticas'),
('Qualidade'),
('Implementação'),
('A infraestrutura'),
('Dados'),
('Táticas'),
('Soluções'),
('Prestação de contas'),
('Funcionalidade'),
('Dados'),
('Dados');